O_bringup: Disable vl5310 laser driver for build.
Function msm_camera_get_dt_gpio_set_tbl() is removed by qcom commit:

723c93d msm: camera: Update camera drivers from 3.18.

+++
../../../../../../kernel/drivers/input/misc/vl53L0/stmvl53l0_module-i2c.c: In function 'stmvl53l0_get_dt_data':
../../../../../../kernel/drivers/input/misc/vl53L0/stmvl53l0_module-i2c.c:188:4: error: implicit declaration of function 'msm_camera_get_dt_gpio_set_tbl' [-Werror=implicit-function-declaration]
    rc = msm_camera_get_dt_gpio_set_tbl(of_node, gconf,
    ^
cc1: some warnings being treated as errors
+++
TODO: Need to re-work on driver then we can enable it back.

Change-Id: Ic3a14eeec090225c6bc33e45d0dbe055c82c1b95
Signed-off-by: a7301c <a7301c@motorola.com>